version: "3.5"
services:
  bot:
    image: notifications_devman
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/notifications_devman
    env_file:
      - .env
    command:
      - "python"
      - "main.py"